// import type { Metadata } from "next";
"use client";

import localFont from "next/font/local";
import "./globals.css";
import { Provider } from "react-redux";
import { store, persistor } from "@/app/redux/store/index";
import { PersistGate } from "redux-persist/integration/react";
import SessionExpiryCheck from './SessionExpiryCheck';  // Import the session expiry check component


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <Provider store={store}>
      <PersistGate loading={null} persistor={persistor}>
        <html lang="en">
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
            <SessionExpiryCheck />
            {children}
          </body>
        </html>
      </PersistGate>
    </Provider>
  );
}
